In [1]:
# 모듈 불러오기
import numpy as np

In [12]:
# 배열(리스트) 데이터와 숫자 데이터의 차이
# 리스트에 있는 숫자의 특징
data1 = [1, 2, 3, 4, 5]
data2 = [4, 5, 6, 7, 8]
print(data1)
sum = data1 + data2
print(sum)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 4, 5, 6, 7, 8]


In [16]:
numdata1 = np.array(data1)
numdata2 = np.array(data2)
print(numdata1)
print(numdata2)
sum = numdata1 + numdata2
print(sum)
sum = numdata1 - numdata2
print(sum)
sum = numdata1 * numdata2
print(sum)
sum = numdata1 / numdata2
print(sum)

[1 2 3 4 5]
[4 5 6 7 8]
[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]
[0.25       0.4        0.5        0.57142857 0.625     ]


In [20]:
# numpy 배열의 형태와 크기를 보여준다
print(numdata1.shape)
# 타입
print(numdata1.dtype)

(5,)
int32


In [27]:
face = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 13]
]
face_data = np.array(face)
print(face_data.shape)

(4, 3)


In [28]:
sum = face_data + 10
print(sum)
sum = face_data * 10
print(sum)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 23]]
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 130]]


In [33]:
num10 = np.zeros(10)
print(num10)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
num1 = np.ones((10, 5))
print(num1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
number = np.arange(10)
print(number)
number = np.arange(1, 11)
print(number)
number = np.arange(10, 21, 2)
print(number)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 12 14 16 18 20]


In [55]:
number[0:2]

array([10, 12])

In [57]:
# 5. Array boolean 인덱싱(마스크)
names = ['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo']
names_array = np.array(names)
print(names_array)
names_array

['Beomwoo' 'Beomwoo' 'Kim' 'Joan' 'Lee' 'Beomwoo' 'Park' 'Beomwoo']


array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [61]:
names_array[3]*2

'JoanJoan'

In [77]:
data = np.random.randn(8, 4)
print(data)

[[ 0.0964247   0.69427578 -0.49027525  0.33142626]
 [ 0.42966156 -0.7842632  -0.33303789  1.24844399]
 [-0.88845911  2.00007258 -0.13372733  0.50977905]
 [-0.19830898  2.54211013  0.65827148  0.26968435]
 [ 0.22061798 -0.31610221  1.13826988 -1.374607  ]
 [-0.07495744  0.74831625  0.75952343  0.25008569]
 [-1.79093267 -0.51907798 -2.42955567 -0.43204259]
 [-1.34151361 -0.25445637 -0.96987307  0.06189965]]


In [96]:
# 마스크 생성
mask1 = (names_array == 'Beomwoo') | (names_array == 'Kim')
print(mask1)

[ True  True  True False False  True False  True]


In [97]:
data[mask1,:]

array([[ 0.0964247 ,  0.69427578, -0.49027525,  0.33142626],
       [ 0.42966156, -0.7842632 , -0.33303789,  1.24844399],
       [-0.88845911,  2.00007258, -0.13372733,  0.50977905],
       [-0.07495744,  0.74831625,  0.75952343,  0.25008569],
       [-1.34151361, -0.25445637, -0.96987307,  0.06189965]])

In [101]:
row = data[:,0]<0
print(row)
data[row,2:4]

[False False  True  True False  True  True  True]


array([[-0.13372733,  0.50977905],
       [ 0.65827148,  0.26968435],
       [ 0.75952343,  0.25008569],
       [-2.42955567, -0.43204259],
       [-0.96987307,  0.06189965]])

In [103]:
# Num 함수
# 수학관련 함수 제공 : 행렬에서 가능한 함수

In [105]:
matrix = np.random.randn(5,3)
print(matrix)

[[ 0.87580649  0.82232907  0.84000864]
 [-0.35064655 -1.16992502  0.70087026]
 [ 2.08989002  1.71885063 -0.20518968]
 [ 1.22160322  0.60780219 -0.14747513]
 [-0.67224521  0.61584241 -1.57167636]]


In [110]:
np.abs(matrix)

array([[0.87580649, 0.82232907, 0.84000864],
       [0.35064655, 1.16992502, 0.70087026],
       [2.08989002, 1.71885063, 0.20518968],
       [1.22160322, 0.60780219, 0.14747513],
       [0.67224521, 0.61584241, 1.57167636]])

In [114]:
row = matrix[1,:] < 0
print(row)
row = matrix[2,:] < 0
print(row)
row = matrix[:,1] < 0
print(row)

[ True  True False]
[False False  True]
[False  True False False False]


In [116]:
np.sign(matrix)

array([[ 1.,  1.,  1.],
       [-1., -1.,  1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1.,  1., -1.]])

In [118]:
np.ceil(matrix)

array([[ 1.,  1.,  1.],
       [-0., -1.,  1.],
       [ 3.,  2., -0.],
       [ 2.,  1., -0.],
       [-0.,  1., -1.]])

In [120]:
np.floor(matrix)

array([[ 0.,  0.,  0.],
       [-1., -2.,  0.],
       [ 2.,  1., -1.],
       [ 1.,  0., -1.],
       [-1.,  0., -2.]])

In [122]:
a = np.log(matrix)
print(a)
np.isnan(a) # nan : not a number, 계산 불가능

[[-0.13261011 -0.19561463 -0.1743431 ]
 [        nan         nan -0.35543249]
 [ 0.73711144  0.54165583         nan]
 [ 0.20016411 -0.4979058          nan]
 [        nan -0.48476417         nan]]


C:\Users\Administrator\AppData\Local\Temp\ipykernel_5736\2462794620.py:1: RuntimeWarning: invalid value encountered in log
  a = np.log(matrix)


array([[False, False, False],
       [ True,  True, False],
       [False, False,  True],
       [False, False,  True],
       [ True, False,  True]])